### ISSUE TITLE
Generator not working in new version of Photoshop (v20.0.0)

### ISSUE THREAD

**Issue by Worksofheart** [adobe-photoshop/generator-assets#452]
Hi everyone,

Since the new version of Photoshop CC 2019 (v20.0.0, released in October 2018) I can't get the Generator to load into Photoshop. The log gives this specific error: 

`[error:app 12:38:01.274 C:\Program Files\Adobe\Adobe Photoshop CC 2019\Required\Generator-builtin\app.js:309:37] Unable to load plugin at 'C:\Program Files\Adobe\Adobe Photoshop CC 2019\Plug-Ins\Generator\Generator AbbeyCore': Could not load plugin at path 'C:\Program Files\Adobe\Adobe Photoshop CC 2019\Plug-Ins\Generator\Generator AbbeyCore': Cannot find module 'internal/util/types'`

The Generator works perfectly fine in the previous version of Photoshop CC 2018 (v19.1.6), with no issues. 

Can you tell me if there's anything I can do to get the Generator to function again? Or whether or not it might be an issue that you can pick up? 

Thanks in advance,

**Comment by mcilroyc** [comment]
@Worksofheart Photoshop 2019 now includes node.js v8.11.1.  Please try running `npm install` for your plugin using node 8.x to see if that resolves the issue.

**Comment by Worksofheart** [comment]
Stil the same problem. These are the versions I'm using
```
>node -v
v8.11.1

>npm -v
5.6.0
```

I deleted the `node_modules` folder and reran `npm i` in the plugin folder. 

Still results in this error:
```
[info:core 18:00:44.408 C:\Program Files\Adobe\Adobe Photoshop CC 2019\Required\Generator-builtin\lib\generator.js:1915:26] Loading plugin: generator-assets (v3.0.0-dev) from: C:\Program Files\Adobe\Adobe Photoshop CC 2019\Plug-Ins\Generator\generator-assets-master
[error:app 18:00:44.452 C:\Program Files\Adobe\Adobe Photoshop CC 2019\Required\Generator-builtin\app.js:309:37] Unable to load plugin at 'C:\Program Files\Adobe\Adobe Photoshop CC 2019\Plug-Ins\Generator\generator-assets-master': Could not load plugin at path 'C:\Program Files\Adobe\Adobe Photoshop CC 2019\Plug-Ins\Generator\generator-assets-master': Cannot find module 'internal/util/types'
```

Note that the version bundled with Photoshop (v2.9.8) does work:
```
[info:core 18:00:44.453 C:\Program Files\Adobe\Adobe Photoshop CC 2019\Required\Generator-builtin\lib\generator.js:1915:26] Loading plugin: generator-assets (v2.9.8) from: C:\Program Files\Adobe\Adobe Photoshop CC 2019\Required\Plug-Ins\Generator\assets.generate
[warning:core 18:00:44.533 C:\Program Files\Adobe\Adobe Photoshop CC 2019\Required\Generator-builtin\lib\generator.js:904:26] WARNING the imageChanged event is expensive, please consider NOT listening to it
[info:core 18:00:44.534 C:\Program Files\Adobe\Adobe Photoshop CC 2019\Required\Generator-builtin\lib\generator.js:1931:26] Plugin loaded: generator-assets
```

**Comment by mcilroyc** [comment]
@Worksofheart Please use the `2.9` branch of generator-assets. Sorry for the confusion.
https://github.com/adobe-photoshop/generator-assets/tree/2.9

**Comment by Worksofheart** [comment]
That indeed seems to fix it, thanks a lot!
